server:
  port: 80

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.125.136:3306/bbs?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1
      validation-query-timeout: 2000
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 1024Mb


mybatis:
  type-aliases-package: com.zzx.model

#静态资源对外暴露的访问路径
file:
  staticAccessPath: /file/**
  #文件上传目录
  uploadFolder: E:\\file

# 用户默认网盘容量大小 字节 默认2GB
user:
  netdisk:
    size: 2147483648